# Generated by Django 4.2.30 on 2026-09-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'technicians',
            },
        ),
        migrations.CreateModel(
            name='TechnicianService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_services', to='services.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_services', to='technicians.technician')),
            ],
            options={
                'db_table': 'technician_services',
            },
        ),
        migrations.AddField(
            model_name='technician',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='technicians', through='technicians.TechnicianService', to='services.service'),
        ),
    ]
