# Generated by Django 4.2.30 on 2026-09-29 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='technicianservice',
            constraint=models.UniqueConstraint(fields=('technician', 'service'), name='unique_technician_service'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['is_active'], name='technicians_is_acti_db6552_idx'),
        ),
    ]
