# Generated by Django 4.2.30 on 2026-09-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='technicians.technician'),
        ),
        migrations.AddIndex(
            model_name='workinghour',
            index=models.Index(fields=['technician', 'weekday'], name='working_hou_technic_07e526_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='working_hour_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='unavailability',
            index=models.Index(fields=['technician', 'start_datetime'], name='unavailabil_technic_1e55f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='unavailability',
            constraint=models.CheckConstraint(check=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='unavailability_start_before_end'),
        ),
    ]
